matrix:
    include:
      - os: linux
        dist: trusty
        sudo: false
        # We want to avoid virtualenv for now
        language: generic
      - os: osx
        language: generic
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake
      - cmake-data
before_install:
 - if [ "$TRAVIS_OS_NAME" = osx ]; then pip install conan; else pip install --user conan; fi
 - conan remote add libtorrent https://api.bintray.com/conan/rllola80/Libtorrent
install:
  - conan install --build=missing
  - conan build
script:
  - python test.py
